# Generated by Django 4.1.3 on 2022-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="summary", field=models.TextField(blank=True),
        ),
    ]
